'use client';
import { useEffect, useState } from 'react';
import Header from '@/components/Header';
import { apiFetch } from '@/services/api';

export default function AccountSettingsPage() {
  const [profile, setProfile] = useState<any>({});
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [message, setMessage] = useState('');
  const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('access_token')}` });
  useEffect(() => { apiFetch('auth/profile', { headers: auth() }).then(r => r.json()).then(setProfile); }, []);
  const notify = (text: string) => { setMessage(text); setTimeout(() => setMessage(''), 3000); };
  const saveProfile = async () => { const res = await apiFetch('auth/profile', { method: 'PATCH', headers: { ...auth(), 'Content-Type': 'application/json' }, body: JSON.stringify(profile) }); const data = await res.json(); if (!res.ok) return notify(data.message); localStorage.setItem('user', JSON.stringify(data)); window.dispatchEvent(new Event('user-updated')); setProfile(data); notify('Đã cập nhật thông tin.'); };
  const changePassword = async () => { if (!password.currentPassword) return notify('Hãy nhập mật khẩu hiện tại trước.'); if (password.newPassword !== password.confirmPassword) return notify('Mật khẩu xác nhận không khớp.'); const res = await apiFetch('auth/change-password', { method: 'PATCH', headers: { ...auth(), 'Content-Type': 'application/json' }, body: JSON.stringify(password) }); const data = await res.json(); if (!res.ok) return notify(data.message); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); notify(data.message); };
  const input = 'mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100 disabled:cursor-not-allowed disabled:opacity-50';
  return <div className="min-h-screen bg-slate-50"><Header/>{message && <div className="fixed left-1/2 top-24 z-[100] -translate-x-1/2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white shadow-xl">{message}</div>}<main className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-3xl font-black text-slate-900">Cài đặt tài khoản</h1><p className="mt-2 text-slate-500">Quản lý hồ sơ và bảo mật đăng nhập.</p><div className="mt-8 grid gap-6 lg:grid-cols-2"><Card title="Thông tin cá nhân"><Field label="Họ và tên"><input disabled value={profile.fullName || ''} className={input}/></Field><Field label="Email"><input value={profile.email || ''} onChange={e=>setProfile({...profile,email:e.target.value})} className={input}/></Field><Field label="Số điện thoại"><input maxLength={10} value={profile.phoneNumber || ''} onChange={e=>setProfile({...profile,phoneNumber:e.target.value.replace(/\D/g,'')})} className={input}/></Field><Field label="Ảnh đại diện (URL)"><input value={profile.avatarUrl || ''} onChange={e=>setProfile({...profile,avatarUrl:e.target.value})} className={input}/></Field><button onClick={saveProfile} className="rounded-2xl bg-blue-600 py-3 font-black text-white">Lưu thông tin</button></Card><Card title="🔐 Đổi mật khẩu"><p className="text-sm text-slate-500">Phải nhập đúng mật khẩu hiện tại trước khi đặt mật khẩu mới.</p><Field label="Mật khẩu hiện tại"><input type="password" value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})} className={input}/></Field><Field label="Mật khẩu mới"><input type="password" disabled={!password.currentPassword} value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})} className={input}/></Field><Field label="Nhập lại mật khẩu mới"><input type="password" disabled={!password.currentPassword} value={password.confirmPassword} onChange={e=>setPassword({...password,confirmPassword:e.target.value})} className={input}/></Field><button disabled={!password.currentPassword || !password.newPassword} onClick={changePassword} className="rounded-2xl bg-slate-900 py-3 font-black text-white disabled:opacity-40">Cập nhật mật khẩu</button></Card></div></main></div>;
}
function Card({title,children}:{title:string;children:React.ReactNode}) { return <section className="grid gap-4 rounded-3xl border border-slate-100 bg-white p-7 shadow-sm"><h2 className="text-xl font-black text-slate-900">{title}</h2>{children}</section>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="text-sm font-bold text-slate-700">{label}{children}</label>; }
