'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import Header from '@/components/Header';
import { apiUrl } from '@/services/api';

const txLabels: Record<string,string> = { VERIFYING:'Chờ xác nhận',SUCCESS:'Đã giao dịch',DISPUTE:'Đang đối soát',CANCELLED:'Chưa giao dịch',PENDING_CANCEL:'Chờ hủy',CANCELLED_AFTER_SUCCESS:'Đã hủy sau giao dịch',FRAUD:'Có dấu hiệu gian lận' };
const invLabels: Record<string,string> = { DRAFT:'Chờ admin phát hành',PENDING_PAYMENT:'Chờ thanh toán',PAID:'Đã thanh toán',OVERDUE:'Quá hạn',CANCELLED:'Đã hủy' };

export default function TransactionsAndInvoicesPage(){
 const [tab,setTab]=useState<'transactions'|'invoices'>('transactions'); const [transactions,setTransactions]=useState<any[]>([]); const [invoices,setInvoices]=useState<any[]>([]); const [user,setUser]=useState<any>(); const [loading,setLoading]=useState(true); const [popup,setPopup]=useState<string|null>(null);
 const load=useCallback(async()=>{ const token=localStorage.getItem('access_token'), stored=localStorage.getItem('user'); if(!token||!stored){setLoading(false);return;} setUser(JSON.parse(stored)); const headers={Authorization:`Bearer ${token}`}; try{const [a,b]=await Promise.all([fetch(apiUrl('transactions/my-transactions'),{headers,cache:'no-store'}),fetch(apiUrl('transactions/my-invoices'),{headers,cache:'no-store'})]); if(a.ok)setTransactions(await a.json()); if(b.ok)setInvoices(await b.json());}finally{setLoading(false)} },[]);
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[load]);
 const notify=(m:string)=>{setPopup(m);setTimeout(()=>setPopup(null),3000)};
 const requestCancel=async(id:string)=>{const reason=window.prompt('Nhập lý do hủy giao dịch sau khi gặp mặt:');if(!reason?.trim())return;const token=localStorage.getItem('access_token');const res=await fetch(apiUrl(`transactions/${id}/request-cancel`),{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({reason})});const data=await res.json().catch(()=>({}));notify(res.ok?'Đã gửi yêu cầu hủy tới đối tác.':data.message||'Không thể gửi yêu cầu.');if(res.ok)load()};
 const respondCancel=async(id:string,isAgreed:boolean)=>{const token=localStorage.getItem('access_token');const res=await fetch(apiUrl(`transactions/${id}/respond-cancel`),{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({isAgreed})});const data=await res.json().catch(()=>({}));notify(res.ok?(isAgreed?'Đã đồng ý hủy giao dịch.':'Đã chuyển tranh chấp tới admin.'):data.message||'Không thể xử lý.');if(res.ok)load()};
 const pay=async(id:string)=>{const token=localStorage.getItem('access_token');const res=await fetch(apiUrl('payments/pay-invoice'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({invoiceId:id})});const data=await res.json();if(res.ok&&data.paymentUrl)location.href=data.paymentUrl;else notify(data.message||'Không thể tạo phiên thanh toán.');};
 if(loading)return <div className="min-h-screen bg-slate-50"><Header/><div className="grid min-h-[60vh] place-items-center font-bold text-blue-600">Đang tải dữ liệu...</div></div>;
 return <div className="min-h-screen bg-slate-50"><Header/>{popup&&<div className="fixed left-1/2 top-24 z-[100] -translate-x-1/2 rounded-2xl bg-rose-600 px-6 py-4 text-sm font-bold text-white shadow-2xl">{popup}</div>}<main className="mx-auto max-w-6xl px-4 py-10">
  <section className="rounded-[2rem] bg-gradient-to-br from-slate-950 to-blue-900 p-8 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-200">Tài chính cá nhân</p><h1 className="mt-2 text-3xl font-black">Lịch sử giao dịch & hóa đơn</h1><p className="mt-2 text-sm text-blue-100">Thanh toán trong 30 ngày. Sau hạn, phí chậm thanh toán là 0,5% phí gốc cho mỗi tháng trễ.</p></section>
  <div className="mt-6 inline-flex rounded-2xl border bg-white p-1.5"><button onClick={()=>setTab('transactions')} className={`rounded-xl px-5 py-2.5 text-sm font-bold ${tab==='transactions'?'bg-blue-600 text-white':'text-slate-500'}`}>Lịch sử giao dịch</button><button onClick={()=>setTab('invoices')} className={`rounded-xl px-5 py-2.5 text-sm font-bold ${tab==='invoices'?'bg-blue-600 text-white':'text-slate-500'}`}>Hóa đơn ({invoices.filter(i=>i.status==='PENDING_PAYMENT').length})</button></div>
  <div className="mt-5 grid gap-4">{tab==='transactions'?transactions.map(tx=><article key={tx.id} className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm md:flex-row md:items-center"><img src={tx.post?.thumbnail||'https://via.placeholder.com/160'} className="h-20 w-28 rounded-xl object-cover" alt=""/><div className="flex-1"><Link href={`/posts/${tx.postId}`} className="font-black text-slate-900 hover:text-blue-600">{tx.post?.title||'Tin bất động sản'}</Link><p className="mt-1 text-sm text-slate-500">{tx.buyerId===user?.id?'Vai trò: Người mua':'Vai trò: Người bán'}</p></div><span className="rounded-full bg-blue-50 px-4 py-2 text-xs font-black text-blue-700">{txLabels[tx.status]||tx.status}</span><div className="flex gap-2">{tx.status==='SUCCESS'&&<button onClick={()=>requestCancel(tx.id)} className="rounded-xl bg-rose-50 px-4 py-2 text-xs font-bold text-rose-600">Yêu cầu hủy</button>}{tx.status==='PENDING_CANCEL'&&tx.cancelInitiatorId!==user?.id&&<><button onClick={()=>respondCancel(tx.id,true)} className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold">Đồng ý hủy</button><button onClick={()=>respondCancel(tx.id,false)} className="rounded-xl bg-rose-600 px-3 py-2 text-xs font-bold text-white">Phản đối</button></>}</div></article>):invoices.map(inv=><article key={inv.id} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="flex-1"><Link href={`/posts/${inv.transaction?.post?.id}`} className="text-lg font-black text-slate-900 hover:text-blue-600">{inv.transaction?.post?.title||'Tin bất động sản'}</Link><p className="mt-2 text-sm text-slate-500">Hạn thanh toán: <b>{inv.dueDate?new Date(inv.dueDate).toLocaleDateString('vi-VN'):'Chờ phát hành'}</b></p>{inv.overdueMonths>0&&<p className="mt-1 text-sm font-bold text-rose-600">Trễ {inv.overdueMonths} tháng · Phí chậm {Number(inv.lateFee).toLocaleString('vi-VN')} ₫</p>}</div><div className="md:text-right"><p className="text-xs font-bold uppercase text-slate-400">Tổng thanh toán</p><p className="text-2xl font-black text-blue-700">{Number(inv.totalPayable).toLocaleString('vi-VN')} ₫</p><span className="text-xs font-bold text-slate-500">{invLabels[inv.status]||inv.status}</span></div>{['PENDING_PAYMENT','OVERDUE'].includes(inv.status)&&<button onClick={()=>pay(inv.id)} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white">Thanh toán ngay</button>}</div></article>)}{((tab==='transactions'&&!transactions.length)||(tab==='invoices'&&!invoices.length))&&<div className="rounded-2xl bg-white p-12 text-center text-slate-400">Chưa có dữ liệu.</div>}</div>
 </main></div>;
}
