'use client';
import { useEffect, useState } from 'react';
import Header from '@/components/Header';
import { apiFetch } from '@/services/api';

export default function SettingsPage(){const [form,setForm]=useState<any>({fullName:'',email:'',phoneNumber:'',avatarUrl:''});const [saving,setSaving]=useState(false);const [popup,setPopup]=useState<{text:string;ok:boolean}|null>(null);
 useEffect(()=>{const token=localStorage.getItem('access_token');apiFetch('auth/profile',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}).then(r=>r.json()).then(setForm)},[]);
 const save=async()=>{setSaving(true);const token=localStorage.getItem('access_token');const res=await apiFetch('auth/profile',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({email:form.email,phoneNumber:form.phoneNumber,avatarUrl:form.avatarUrl})});const data=await res.json();if(res.ok){localStorage.setItem('user',JSON.stringify(data));window.dispatchEvent(new Event('user-updated'));setForm(data);setPopup({text:'Đã cập nhật thông tin.',ok:true})}else setPopup({text:data.message||'Cập nhật thất bại.',ok:false});setSaving(false);setTimeout(()=>setPopup(null),3000)};
 return <div className="min-h-screen bg-slate-50"><Header/>{popup&&<div className={`fixed left-1/2 top-24 z-[100] -translate-x-1/2 rounded-xl px-6 py-3 font-bold text-white ${popup.ok?'bg-emerald-600':'bg-rose-600'}`}>{popup.text}</div>}<main className="mx-auto max-w-2xl px-4 py-10"><div className="rounded-[2rem] border bg-white p-8 shadow-sm"><h1 className="text-3xl font-black text-slate-900">Cài đặt tài khoản</h1><p className="mt-2 text-sm text-slate-500">Tên tài khoản được giữ cố định để đảm bảo lịch sử giao dịch minh bạch.</p><div className="mt-8 grid gap-5"><label className="text-sm font-bold text-slate-700">Họ và tên<input disabled value={form.fullName||''} className="mt-2 w-full rounded-xl border bg-slate-100 px-4 py-3 text-slate-500"/></label><label className="text-sm font-bold text-slate-700">Email<input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-700">Số điện thoại<input maxLength={10} value={form.phoneNumber||''} onChange={e=>setForm({...form,phoneNumber:e.target.value.replace(/\D/g,'')})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold text-slate-700">Ảnh đại diện (URL)<input value={form.avatarUrl||''} onChange={e=>setForm({...form,avatarUrl:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><button disabled={saving} onClick={save} className="rounded-xl bg-blue-600 py-3 font-black text-white disabled:opacity-50">{saving?'Đang lưu...':'Lưu thay đổi'}</button></div></div></main></div>}
